config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    authenticated :user do
      root to: 'servants#index'
    end
    unauthenticated :user do
      root to: 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  resources :servants
  resources :rank
end

app/models/rank.rb
class Rank < ActiveRecord::Base
  has_many :servants
  validates :name, :level, presence: true, uniqueness: true
  validates :header_color, presence: true
end

app/models/servant.rb
class Servant < ActiveRecord::Base
  STATUS_TYPE = {active: true, inactive: false}

  mount_uploader :avatar, AvatarUploader
  belongs_to :rank

  validates :nick, :rank, presence: true

  def self.ordered
    joins(:rank).order('rank.level ASC, servants.status DESC, servants.name ASC')
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  decent_configuration do
    strategy DecentExposure::StrongParametersStrategy
  end
end

app/controllers/rank_controller.rb
class RankController < ApplicationController
  expose(:rank_all) { Rank.all }
  expose(:rank, ancestor: :rank_all, attributes: :rank_params)

  def create
    if rank.save
      redirect_to_index
    else
      render :new
    end
  end

  def update
    if rank.save
      redirect_to_index
    else
      render :edit
    end
  end

  def destroy
    rank.destroy
    redirect_to_index
  end

  private

  def rank_params
    params.require(:rank).permit!
  end

  def redirect_to_index
    redirect_to rank_index_path
  end
end

app/controllers/servants_controller.rb
class ServantsController < ApplicationController
  expose(:servants) { Servant.ordered }
  expose(:servant, attributes: :servant_params)
  expose(:status_type) { Servant::STATUS_TYPE }

  def create
    if servant.save
      redirect_to_index
    else
      render :new
    end
  end

  def update
    if servant.save
      redirect_to_index
    else
      render :edit
    end
  end

  def destroy
    servant.destroy
    redirect_to_index
  end

  private

  def servant_params
    params.require(:servant).permit!
  end

  def redirect_to_index
    redirect_to servants_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"}
      %button.close{'aria-hidden' => 'true', 'data-dismiss' => 'alert', :type => 'button'} ×
      = content_tag :div, msg, id: "flash_#{name}"

app/views/layouts/_navigation.html.haml
.navbar.navbar-inverse.navbar-fixed-top{role: 'navigation'}
  .container
    .navbar-header
      %button.navbar-toggle.collapsed{'data-target' => '.navbar-collapse', 'data-toggle' => 'collapse', type: 'button'}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to 'AZM PANEL', root_path , class: 'navbar-brand'
    -if user_signed_in?
      .navbar-collapse.collapse
        %ul.nav.navbar-nav
          = render 'layouts/navigation_left'
        %ul.navbar-form.navbar-right
          = render 'layouts/navigation_right'

app/views/layouts/_navigation_left.html.haml
%li{ class: ('active' if current_page?(servants_path)) }
  =link_to t('pages.servants.servants'), servants_path
%li{ class: ('active' if current_page?(rank_index_path)) }
  =link_to t('pages.rank.rank' ), rank_index_path

app/views/layouts/_navigation_right.html.haml
%li
  =link_to t('global.log_out'), destroy_user_session_path, method: :delete, class: 'btn btn-success'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: 'width=device-width, initial-scale=1.0', name: 'viewport'}/
    %title= content_for?(:title) ? yield(:title) : 'Azm Panel'
    %meta{content: content_for?(:description) ? yield(:description) : 'Azm Panel', name: 'description'}/
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = render 'layouts/navigation'
    %main{role: 'main'}
      = render 'layouts/messages'
      = yield
  = javascript_include_tag 'application', 'data-turbolinks-track' => true

app/views/rank/_fields.html.haml
-if rank.errors.size > 0
  .alert.alert-danger
    = f.semantic_errors :name, :level
= f.input :name
= f.input :short_name
= f.input :level
= f.input :header_color

app/views/rank/edit.html.haml
.panel.panel-primary
  .panel-heading= t('pages.rank.rank_details')
  .panel-body
    = semantic_form_for rank do |f|
      = render 'fields', f: f
      = f.button t('pages.actions.update'), class: 'btn btn-warning'
= link_to t('global.back'), rank_index_path, class: 'btn'

app/views/rank/index.html.haml
= link_to t('pages.rank.add'), new_rank_path, class: 'btn btn-success'

%table.table.table-striped
  %thead
    %tr
      %th
        = t('pages.tables.no')
      %th
        = t('pages.tables.name')
      %th
        = t('pages.rank.short_name')
      %th
        = t('pages.rank.level')
      %th
        = t('pages.rank.header_color')
      %th
        = t('pages.actions.actions')
  %tbody
    - rank_all.each_with_index do |rank, index|
      %tr
        %td
          = index + 1
        %td
          = link_to rank.name, rank_path(rank)
        %td
          = rank.short_name
        %td
          = rank.level
        %td
          = rank.header_color
        %td
          = link_to t('pages.actions.edit'), edit_rank_path(rank), class: 'btn btn-primary'
          = link_to t('pages.actions.delete'), rank_path(rank), method: :delete, class: 'btn btn-danger'

app/views/rank/new.html.haml
.panel.panel-primary
  .panel-heading= t('pages.rank.rank_details')
  .panel-body
    = semantic_form_for rank do |f|
      = render 'fields', f: f
      = f.button t('pages.actions.save'), class: 'btn btn-success'
= link_to t('global.back'), rank_index_path, class: 'btn'

app/views/servants/_fields.html.haml
-if servant.errors.size > 0
  .alert.alert-danger
    = f.semantic_errors :name, :level
= f.input :avatar
= image_tag(servant.avatar_url, class: 'img-thumbnail') if servant.avatar?
= f.hidden_field :avatar_cache
= f.input :nick
= f.input :rank, prompt: t('pages.servants.select_rank')
= f.input :name
= f.input :in_from, as: :date_picker, input_html: { class: 'date' }
= f.input :year_of_birth, as: :date_picker, input_html: { class: 'year' }
= f.input :city
= f.input :battle_tag
= f.input :status, as: :radio, collection: status_type

app/views/servants/edit.html.haml
.panel.panel-primary
  .panel-heading= t('pages.servants.servant_details')
  .panel-body
    = semantic_form_for servant do |f|
      = render 'fields', f: f
      = f.button t('pages.actions.update'), class: 'btn btn-warning'
= link_to t('global.back'), servants_path, class: 'btn'

app/views/servants/index.html.haml
= link_to t('pages.servants.add'), new_servant_path, class: 'btn btn-success'

%table.table.table-striped
  %thead
    %tr
      %th
        = t('pages.tables.no')
      %th
        = t('pages.servants.nick')
      %th
        = t('pages.servants.rank')
      %th
        = t('pages.tables.name')
      %th
        = t('pages.servants.battle_tag')
      %th
        = t('pages.servants.status')
      %th
        = t('pages.actions.actions')
  %tbody
    - servants.each_with_index do |servant, index|
      %tr
        %td
          = index + 1
        %td
          = link_to servant.nick, servant_path(servant)
        %td
          = servant.rank.name
        %td
          = servant.name
        %td
          = servant.battle_tag
        %td
          = servant.status
        %td
          = link_to t('pages.actions.edit'), edit_servant_path(servant), class: 'btn btn-primary'
          = link_to t('pages.actions.delete'), servant_path(servant), method: :delete, class: 'btn btn-danger'

app/views/servants/new.html.haml
.panel.panel-primary
  .panel-heading= t('pages.servants.servant_details')
  .panel-body
    = semantic_form_for servant do |f|
      = render 'fields', f: f
      = f.button :submit, class: 'btn btn-success'
= link_to t('global.back'), servants_path, class: 'btn'

app/views/servants/show.html.haml
%table.table.table-striped
  %thead
    %tr
      %th{colspan: '2'}
        = t('pages.servants.servant_details')
  %tbody
    %tr
      %td
        = t('pages.servants.avatar')
      %td
        = image_tag(servant.avatar_url) if servant.avatar?
    %tr
      %td
        = t('pages.servants.nick')
      %td
        = servant.nick
    %tr
      %td
        = t('pages.servants.rank')
      %td
        = servant.rank.name
    %tr
      %td
        = t('pages.servants.name')
      %td
        = servant.name
    %tr
      %td
        = t('pages.servants.how_long')
      %td
        = servant.in_from
    %tr
      %td
        = t('pages.servants.year_of_birth')
      %td
        = servant.year_of_birth
    %tr
      %td
        = t('pages.servants.city')
      %td
        = servant.city
    %tr
      %td
        = t('pages.servants.battle_tag')
      %td
        = servant.battle_tag
    %tr
      %td
        = t('pages.servants.status')
      %td
        = servant.status
    %tr
      %td{colspan: '2'}
        = link_to t('pages.actions.edit'), edit_servant_path(servant), class: 'btn btn-primary'
        = link_to t('pages.actions.delete'), servant_path(servant), method: :delete, class: 'btn btn-danger'
= link_to t('global.back'), servants_path, class: 'btn'